/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.6.11 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('87','Othercharges','Othercharges','C','16','Othercharges');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('86','GST','GSTmaster','C','16','GSTmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('85','GST Tax Invoices','GSTtaxinvoice','C','27','GSTtaxinvoice');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('84','Purchase Register - Group Wise','purchaseregistergroupwise','C','31','purchaseregistergroupwise');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('83','Rawmaterial Register - Product Wise','rawmaterialproductwise','C','31','rawmaterialproductwise');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('82','Purchase Register - All','purchaseregnew','C','31','purchaseregnew');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('81','Finishproduct Stock','finishproductstock','C','31','finishproductstock');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('80','Finish product purchase','finishproductpurchase','C','27','finishproductpurchase');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('79','Rawmaterial Stock','rawmaterialstock','C','31','rawmaterialstock');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('78','Rawmaterial Consumption','rawmaterialconsumption','C','3','rawmaterialconsumption');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('77','Closing Transfer (A/C)','accountclosingtransfer','C','76','accountclosingtransfer');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('76','Utility',NULL,'P',NULL,'Utility');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('75','Trial - Debitor/Creditor','sundrycreddebtrtrial','C','66','sundrycreddebtrtrial');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('74','Debtors Outstanding','debitoroutstanding','C','66','debitoroutstanding');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('73','Creditors Outstanding','creditorsoutstanding','C','66','creditorsoutstanding');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('72','General Ledger','generalledgerreport','C','66','generalledgerreport');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('71','Customer Receipt','customerpayment','C','65','customerpayment');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('70','Customer Adjustment','customeradvanceadjustment','C','65','customeradvanceadjustment');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('69','Customer Advance','customeradvance','C','65','customeradvance');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('68','Trial Balance ','trialbalancedetail','C','66','trialbalancedetail');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('67','Trial Balance (Account Wise)','trialbalance','C','66','trialbalance');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('66','Account Statement','accountstatement','SC','31','');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('65','Payment & Advance',NULL,'P',NULL,NULL);
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('64','Vendor Payment','vendorpayment','C','65','vendorpayment');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('63','Vendor Adjustment','vendoradvanceadjustment','C','65','vendoradvanceadjustment');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('62','Vendor Advance','vendoradvance','C','65','vendoradvance');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('61','Challan Wise Incoming Report','challanwisereport','C','31','challanwisereport');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('60','Sales Tax Register','saletaxregister','C','31','saletaxregister');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('59','Garden Tea Sale','rawteasale','C','27','rawteasale');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('58','Voucherlist','voucherlist','C','16','voucherlist');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('57','Stock Transfer(OUT)','stocktransferout','C','27','stocktransferout');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('56','Stock Transfer(IN)','stocktransferin','C','27','stocktransferin');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('55','Finished Product OP Stock','finishedproductopeningstock','C','3','finishedproductopeningstock');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('54','Raw Material Register','rawmaterialregister','C','31','rawmaterialregister');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('53','SaleBill Register','salebillregister','C','31','salebillregister');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('52','Branch','branchmaster','C','3','branchmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('51','Purchase Raw Material','rawmaterialpurchase','C','27','rawmaterialpurchase');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('50','Excise','excisemaster','C','3','excisemaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('49','Raw Material','rawmaterial','C','3','rawmaterial');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('48','Journal Voucher','journalvoucher','C','27','journalvoucher');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('47','Contra Voucher','contravoucher','C','27','contravoucher');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('46','General Voucher','generalvoucher','C','27','generalvoucher');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('45','Subledger','subledger','C','3','subledger');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('44','Unit','unitmaster','C','3','unitmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('43','Invoice Status','invoicestatus','C','42','invoicestatus');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('42','MIS',NULL,'P',NULL,NULL);
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('41','Opening Balance - Invoice','openingbalance','C','3','openingbalance');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('40','Stock with Transporter','stockwithtransporter','C','31','stockwithregister');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('39','Purchase Register','purchaseregister','C','31','purchaseregister');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('38','Company','companymaster','C','3','companymaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('37','Product Rate & Net','productpacketrate','C','3','productpacketrate');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('36','Tax Invoice','taxinvoice','C','27','taxinvoice');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('35','Finish Product','finishproduct','C','27','finishproduct');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('34','Blending','blending','C','27','blending');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('33','Short Adjustment','shortageadjustment','C','27','shortageadjustment');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('32','Auction Area','auctionarea','C','3','auctionarea');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('31','Report',NULL,'P',NULL,NULL);
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('30','product Creation','product','C','3','product');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('29','Packet','packet','C','3','packet');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('28','Stock Summary','stocksummery','C','31','stocksummery');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('27','Transaction',NULL,'P',NULL,NULL);
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('26','Location','locationmaster','C','3','locationmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('25','Transporter to Buyer','doproductrecv','C','27','doproductrecv');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('24','Send Do to Transporter','deliveryordertotransp','C','27','deliveryordertotransp');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('20','Tea Group','teagroupmaster','C','3','teagroupmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('19','Transport','transportmaster','C','3','transportmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('18','Customer','customermaster','C','3','customermaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('17','CST','cstmaster','C','16','cstmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('16','Accounts','acconuts','SC','3','');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('15','Receiving DO','unreleaseddo','C','27','unreleaseddo');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('14','Purchase Invoice','purchaseinvoice','C','27','purchaseinvoice');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('13','Vendor','vendormaster','C','3','vendormaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('12','Account','accountmaster','C','16','accountmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('11','Group Master','groupmaster','C','16','groupmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('10','Group Category','groupcategorymaster','C','16','groupcategorymaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('9','VAT','vatmaster','C','16','vatmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('8','Broker','brokermaster','C','3','brokermaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('7','Service Tax','servicetaxmaster','C','16','servicetaxmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('6','Warehouse','warehousemaster','C','3','warehousemaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('5','Grade','grademaster','C','3','grademaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('4','Garden','gardenmaster','C','3','gardenmaster');
insert into `menu` (`id`, `menu_name`, `menu_link`, `is_parent`, `parent_id`, `menu_code`) values('3','Get Ready','','P',NULL,NULL);
